mgr/dashboard: fix missing service invocation
Resolves: rhbz#2351028

Fixes the below error
```

Error: src/app/ceph/dashboard-v3/dashboard/dashboard-v3.component.ts:195:17 - error TS2339: Property 'mgrModuleService' does not exist on type 'DashboardV3Component'.

195     return this.mgrModuleService.getConfig('cephadm').pipe(
                    ~~~~~~~~~~~~~~~~

```

Signed-off-by: Nizamudeen A <nia@redhat.com>