qa: fix nvmeof upgrade from v20.2.0
Bootstrap fails on v20.2.0 upgrade because of
cephadm binary and ceph image version mismatch.

This fixes following problem in bootstrap by using
tentacle cephadm binary:
```
Error: Container release tentacle != cephadm release umbrella; please use matching version of cephadm (pass --allow-mismatched-release to continue anyway)
```

Fixes: https://tracker.ceph.com/issues/75912

Signed-off-by: Vallari Agrawal <vallari.agrawal@ibm.com>