mgr/dashboard: cypress failure after angular upgrade
Resolves: rhbz#2352840

after angular upgrade, the tests started failing with
An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.
Cannot read properties of undefined (reading 'value')

which seems to originate from the page-helper.po. So handling the
undefined value.

Example run: https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/17541/consoleFull#204663575173a8703b-5adb-41c5-84a0-8cf4e065ba3d

Fixes: https://tracker.ceph.com/issues/68871
Signed-off-by: Nizamudeen A <nia@redhat.com>
(cherry picked from commit a80aa1a84a324296106d4de7f2cb9b3c52b7a134)