mgr/nvmeof: add missing CLICommand to the module
Fixed AttributeError: type object 'NVMeoF' has no attribute 'CLICommand'

Signed-off-by: Avan Thakkar <athakkar@redhat.com>